change gas display
near/near-explorer pull request #415
Opened 2020-09-08 21:44 UTC by icerove

fix #413

2020-09-08 23:58 UTC, bowenwang1996 commented on frontend/src/components/utils/Gas.tsx
> +export const GGAS = new BN(10 ** 9);
We should still have TGAS

2020-09-14 23:08 UTC, frol approved these changes

2020-09-15 13:00 UTC, frol commented on frontend/src/components/utils/Gas.tsx
> +const GGAS = new BN(1024).mul(MGAS);
Why 1024?

I like the idea of defining the next const using the previous one multiplied by 1000.

2020-09-16 10:08 UTC, frol requested changes
^

2020-09-17 09:53 UTC, frol approved these changes

2020-09-25 19:51 UTC, merged