Frontend/fix header
near/near-explorer pull request #483
Opened 2020-11-17 01:33 UTC by icerove

fix header and footer

2020-11-17 21:07 UTC, corwinharrell commented
@jakestutzman can you please provide @icerove with the most up to date NEARkat illustration for use in the explorer footer?

2020-11-18 15:46 UTC, frol commented on frontend/src/components/utils/Footer.jsx
> +<<<<<<< HEAD
You are supposed to resolve merge conflicts, you know :smile:

2020-11-18 16:55 UTC, corwinharrell requested changes
### Issues on Desktop
- [x] Search bar in nav is not centered
- [x] Nav items are not vertically aligned
- [x] Logo should not scale dynamically. It should be one size for desktop, and then a smaller size for tablet/mobile
- [x] There should be some padding between the icons and titles for each nav item.
- [x] Each network should be represented by a different color
- [x] "ChainInfo" is an abbreviation. It is also two words, not one. The original designs use the words "Explore", as this was a suggestion from internal team members. If you have received feedback that this is not an effective title, please share the feedback so we can determine a better alternative.
- [x] The hover and active states for the dropdown menus in the nav are not consistent with the designs
- [x] Styles for the search bar in the navigation are not consistent with the design. (hover/focus states in particular)

### Issues on Mobile
- [x] Logo and network selector are not left and right aligned.
- [x] Primary navigation is not nested within a Menu, but is instead placed under the search bar, which is inconsistent with the designs.

@icerove it seems that most of these issues could be avoided if the implementation would more closely adhere to the designs provided. Could you articulate why there are so many things here that still need to be addressed? What resources or details have you felt are missing in order to be able to accurately implement the designs that were proposed for these changes?

2020-11-27 15:25 UTC, frol requested changes
## Desktop and mobile issues:

The footer is not attached to the bottom of the window:

![Screenshot from 2020-11-27 17-23-07](https://user-images.githubusercontent.com/304265/100463901-58a9dc80-30ab-11eb-9790-844586278851.png)

## Mobile issues:

There is no network dropdown at all.

NEARkat should be together with the "join the community":

![Screenshot from 2020-11-27 17-17-13](https://user-images.githubusercontent.com/304265/100463483-ad992300-30aa-11eb-953c-72aa2562fe84.png)

Top navbar dropdown has different corner styles on hover and without hover:

![image](https://user-images.githubusercontent.com/304265/100463659-f355eb80-30aa-11eb-82ff-170c972ef661.png)

![image](https://user-images.githubusercontent.com/304265/100463698-023c9e00-30ab-11eb-9ded-9893ac44e6da.png)

2020-12-09 00:20 UTC, icerove commented
@frol 
almost finish all feature for the header and footer.
Here are something missing:
1. cannot get the innerwidth so search bar is not showing on the dashboard on mobile.
2. on hover of nav dropdown, the icon color is not changed.

2020-12-09 22:22 UTC, jakestutzman commented
@corwinharrell @icerove @frol I'd like us to make a few tweaks to accommodate a small 'window' for the nearkats to hang out of. Here's what I'm thinking. Any red flags here? 

![image](https://user-images.githubusercontent.com/46854/101695768-b1c62880-3a3a-11eb-940b-bad92984efdb.png)


https://www.figma.com/file/tW2iLtA1psHki0D1vKExf1/Dashboard-Refresh?node-id=0%3A1

2020-12-09 22:23 UTC, jakestutzman commented
Here's the mobile view 
![image](https://user-images.githubusercontent.com/46854/101695885-dd491300-3a3a-11eb-915e-aba2175386cb.png)

2020-12-10 19:58 UTC, corwinharrell commented
@jakestutzman I like the little window idea, but don't know if the border is necessary. We're already calling a lot of attention to this component, so imo, the more subtle the better. Are you opposed at all to omitting it?

2020-12-10 22:27 UTC, icerove commented
@corwinharrell I fix the footer for new design

2020-12-11 16:58 UTC, jakestutzman commented
> @jakestutzman I like the little window idea, but don't know if the border is necessary. We're already calling a lot of attention to this component, so imo, the more subtle the better. Are you opposed at all to omitting it?

I think the outline helps balance the line art of the nearkats. I tried it without and it didn't seem to 'contain' it as well. Feel free to make a final decision on it tho.

2020-12-13 11:34 UTC, frol requested changes
Here are a few discrepancies I notice:

* [ ] The networks dropdown does not match the design when open (the border should not stand out, the width of the dropped down element should match the width of the button, if possible)
* [ ] the border when clicked on the "Explore" dropdown should not be there
* [x] the font-weight on the search field in the top navigation is too light (see the comment about font-weight)
* [x] the footer in mobile version is broken
![image](https://user-images.githubusercontent.com/304265/102010331-2e4b5680-3d1c-11eb-956e-3a5ada8fe17f.png)

2020-12-13 11:34 UTC, frol commented on frontend/src/components/utils/Search.jsx
> +            font-weight: lighter;
Please, remove this rule since it is too light, and it is really hard to read. The default font-weight matches the Figma design.

2020-12-13 14:18 UTC, frol commented
* [ ] the footer is below the screen when the content fits the screen just fine - the footer should be visible if the main content fits the page. Reproduction: https://near-explorer-frontend-pr-483.onrender.com/blocks/qwe

2020-12-18 14:17 UTC, frol commented
@icerove I had unchecked the items that still do not match the design as you asked.

Here is one that is the follow-up to the last item about the footer:

* [ ] The footer on a page with little content should not cause the page to have a vertical scroll

2021-01-08 17:05 UTC, frol approved these changes
Great job!

@corwinharrell could you review the header/footer redesign? https://near-explorer-frontend-pr-483.onrender.com/ How do you feel about releasing this version to production [without the new dashboard] (the new dashboard is in a separate PR at the moment)?

2021-01-08 17:05 UTC, frol commented on frontend/src/pages/_app.jsx
> +            min-height: calc(100vh - 118px);
118px is not enough to avoid vertical scroll on a page where there is not enough content, while 119px works fine

2021-01-08 20:35 UTC, frol commented
@icerove I have reviewed the initial comments from @corwinharrell, and it seems that we still miss a few items. Please, review them and let me know if we cannot/unclear how to address

2021-01-14 22:52 UTC, icerove commented on frontend/src/components/utils/HeaderNavDropdown.jsx
> +  <Dropdown>
need help for this. @frol 
file is HeaderNavDropdown.js

2021-01-14 23:48 UTC, icerove commented on frontend/src/components/utils/Header.jsx
> +          {router.pathname !== "/" ? <Search /> : isMobile ? <Search /> : null}
I change it with your comment, but weird thing happen as on dashboard page, the search box for mobile one is not fit for design on other page. @frol

2021-01-15 16:06 UTC, frol commented on frontend/src/components/utils/Header.jsx
> +          {router.pathname !== "/" ? <Search /> : isMobile ? <Search /> : null}
@icerove Could you provide screenshots? I am not exactly following your concern. It seems to be working fine for me except that on mobile the search box is higher on the dashboard page than on any other page:

![image](https://user-images.githubusercontent.com/304265/104749605-c54b6a00-5731-11eb-9be5-109ef4dd4bda.png)

(the search input is 306x49px)

![image](https://user-images.githubusercontent.com/304265/104749653-d72d0d00-5731-11eb-8e1b-46b4fe666b53.png)

(the search input is 306x40px)

NOTE: The second style is what we want to have everywhere.

2021-01-15 16:08 UTC, frol commented on frontend/src/components/utils/HeaderNavDropdown.jsx
> +  <Dropdown>
It looks good to me now. How can I help there?

2021-01-15 16:20 UTC, frol requested changes
These are the final review notes from me.

@corwinharrell I would love to hear your review. See the deployed staging version here: https://near-explorer-frontend-pr-483.onrender.com/

2021-01-15 16:20 UTC, frol commented on frontend/src/components/utils/HeaderNavDropdown.jsx
> +    <Dropdown.Item className="header-nav-item" href={link}>
We need to use the `<Link>` tag from next.js so the transitions are client-side instead of full reload.

2021-01-15 16:20 UTC, frol commented on frontend/src/components/utils/Search.jsx
> +          .button-search {
Please, fix the `:hover` button background. It is currently somewhat green:
![image](https://user-images.githubusercontent.com/304265/104751480-325fff00-5734-11eb-88c0-6913e00be63e.png)

2021-01-16 23:11 UTC, frol requested changes
* [ ] Please, resolve the merge conflict
* [ ] There are way too many borders on the search input (both on `:hover` and `:active` state): 
![image](https://user-images.githubusercontent.com/304265/104825154-f1044800-5836-11eb-9ed8-3838ff710194.png)

2021-01-19 22:02 UTC, frol requested changes
I wish I could just merge it, but I have to send another changes request :confounded: 

* [ ] ![image](https://user-images.githubusercontent.com/304265/105097805-f6a49c80-5a87-11eb-9e27-4ec23435c068.png)

the border does not match the design

![image](https://user-images.githubusercontent.com/304265/105097934-205dc380-5a88-11eb-8375-5ec0fab03eb6.png)
* [ ] 
![image](https://user-images.githubusercontent.com/304265/105097983-2eabdf80-5a88-11eb-9c61-e463b98c4bfa.png)

the border shifts the input a few pixels on hover and focus and also does not match the design
* [ ] 
![image](https://user-images.githubusercontent.com/304265/105098088-54d17f80-5a88-11eb-8c93-81a6bbfb3a6b.png)

when you click on the Search button, it goes dark green. @corwinharrell what should be the background color for the pressed button?

@icerove please, pair up with @corwinharrell to iterate faster.

2021-01-19 22:06 UTC, frol commented
@icerove Hints about the borders styling:

* use `.parent-block:focus-within .button` to style the border on the block that needs to be styled with the input is focused
* use `.parent-block:hover .button` to style the whole search box when a user hovers over it (instead of only capturing the input hover event itself

2021-01-20 21:22 UTC, corwinharrell commented
@icerove Please let me know if you have any questions regarding the styling issues @frol mentioned above. I'm happy to help in providing the necessary guidance to ensure that the implementation reaches parity with the design.

2021-01-20 22:17 UTC, corwinharrell commented
@icerove I've gone ahead and [styled a version on codepen](https://codepen.io/corwinharrell/pen/XWjQbMd) if you'd like to use it as reference for how this should be implemented.

If you'd like me to go ahead and do this for the search input inside of the header as well, just let me know.

2021-01-22 19:00 UTC, frol approved these changes

2021-01-22 19:10 UTC, frol approved these changes

2021-01-25 15:30 UTC, corwinharrell requested changes
There are still issues with the implementation of the new inputs.

- [ ] The borders and border radii are not consistent and aligned, which results in gaps between the inputs and border at the corners. This is most visible in the focused state:

<img width="782" alt="Screen Shot 2021-01-25 at 10 26 59 AM" src="https://user-images.githubusercontent.com/5934188/105726455-1b6d9980-5ef8-11eb-8e69-9a373ca2ea24.png">

- [ ] In addition, the search input nested in the header also has a different background color than the rest of the input. It's very slight but its there.

<img width="553" alt="Screen Shot 2021-01-25 at 10 27 07 AM" src="https://user-images.githubusercontent.com/5934188/105726632-43f59380-5ef8-11eb-9aad-adc5a63b6e65.png">

2021-01-26 17:57 UTC, corwinharrell requested changes
Almost there. There is a remnant style from the old search input that adds a teal shadow/outline of sorts on the search button when pressed. This should be removed.

<img width="411" alt="Screen Shot 2021-01-26 at 12 55 18 PM" src="https://user-images.githubusercontent.com/5934188/105884425-f7808580-5fd5-11eb-80f9-bc00c9313f67.png">

2021-01-26 19:37 UTC, corwinharrell approved these changes

2021-01-26 19:58 UTC, merged