Feature/dashboard transaction charts
near/near-explorer pull request #507
Opened 2020-12-18 20:51 UTC by icerove

add transaction Count History chart on dashboard

2020-12-22 21:07 UTC, frol requested changes
I guess we are blocked on #483 here.

* [x] The font family and the font-weight do not seem to match the one that is used on Figma
* [x] The arrows are not aligned and the font color does not match the design: 
![image](https://user-images.githubusercontent.com/304265/102933167-86066200-4480-11eb-82e1-74939e9dc81e.png)

2021-01-16 00:25 UTC, icerove commented
1. font family is already changed in the PR #483 
2. yes, it is different from design since the design do not consider the maker for the term explanation and all cell will link to new page will cover the maker that for term explanation.

2021-01-16 09:31 UTC, frol requested changes
Mobile version needs more love:

![image](https://user-images.githubusercontent.com/304265/104808353-4d8f4500-57ee-11eb-8acd-10bb9960d0e6.jpeg)

2021-01-16 09:31 UTC, frol commented on frontend/src/components/utils/ListHandler.tsx
> +                        ? context.latestBlockHeight
Revert these changes, I had fixed it in master already

2021-01-16 09:31 UTC, frol commented on frontend/src/components/utils/Update.tsx
> +      {category === "Block" ? (
Fixed in master

2021-01-16 09:31 UTC, frol commented on frontend/src/context/DatabaseProvider.jsx
> +  latestBlockHeight: 0,
I believe it is already fixed in master

2021-01-19 21:47 UTC, frol approved these changes
I approve it to mark it ready, but we should not merge it before #483. Once #483 is merged, we need to rebase/merge master, and ensure that the look matches the design.

* [ ] The transactions graph needs some styling in terms of font size, color, padding, etc.

2021-01-27 00:16 UTC, icerove commented
please have a look and give comments. @corwinharrell @frol

2021-01-27 18:18 UTC, frol requested changes
* [ ] These are not good defaults: ![image](https://user-images.githubusercontent.com/304265/106035320-a8714800-60dc-11eb-885b-a1c525b9503a.jpeg)
* [ ] We should adjust the graph height, font color, and other minor details that we can tweak, otherwise, explicitly state which parts we cannot tweak

2021-01-28 19:12 UTC, icerove commented
The chart x and y axis and label and tooltip date format since it is the same as x label cannot be exact the same as design. @frol @corwinharrell

2021-01-28 19:38 UTC, frol commented
FYI I am fixing some general layout styling issues here. I will push them later today

2021-01-28 23:53 UTC, frol commented
I have mostly fixed the styling and layout issues, but I broke the colors of the font and the right arrow during the refactoring:

![image](https://user-images.githubusercontent.com/304265/106212953-7201fe80-61aa-11eb-8321-78e94ad22067.png)

It is quite late here, so I am heading to bed.

@corwinharrell It would be great if you can take a glance at the latest version now.

2021-01-29 16:57 UTC, corwinharrell requested changes
This is looking better. Here are some inconsistencies that I identified:

### Desktop

- [x] Search bar width should be the same as the container that wraps the cards

<img width="844" alt="Screen Shot 2021-01-29 at 11 44 35 AM" src="https://user-images.githubusercontent.com/5934188/106302760-5d178080-6227-11eb-8cb7-f2c94708d3c1.png">

- [x] On hover, the metric number should be blue.
- [ ] The padding around the cards should be consistent on all sides. -----Not very sure what this refer to @frol @corwinharrell 

<img width="431" alt="Screen Shot 2021-01-29 at 11 45 07 AM" src="https://user-images.githubusercontent.com/5934188/106302935-905a0f80-6227-11eb-815b-5ef275d91ba9.png">

- [ ] There is a strange flash of a black outline on the network menu onMouseLeave ---- This is from `.show > .btn-secondary.dropdown-toggle` part. I am not sure why this happened. Have a look. 

![Kapture 2021-01-29 at 11 46 43](https://user-images.githubusercontent.com/5934188/106303140-cbf4d980-6227-11eb-9089-d0df2c366a04.gif)

- [x] The styling on the graph does not match the designs. Primarily the borders and step markers. See designs for reference. -----change a lot, the y label cannot be the same and the vertical line is for tooltip and cannot remove.   

### Mobile

- [x] The logo in the header uses the full version instead of the icon version
- [x] The network dropdown is not centered.
- [x] Letter-spacing for the nav items is inconsistent
- [x] The expanded menu is not positioned correctly (no space between menu and search bar.
- [x] There is excessive padding on the left and right sides of the expanded menu

<img width="372" alt="Screen Shot 2021-01-29 at 11 50 35 AM" src="https://user-images.githubusercontent.com/5934188/106303752-7ff66480-6228-11eb-8f91-22599245a4b5.png">

- [x] The card headers are broken and wrap on mobile

<img width="372" alt="Screen Shot 2021-01-29 at 11 53 21 AM" src="https://user-images.githubusercontent.com/5934188/106303830-9997ac00-6228-11eb-9440-bb7773cfbda9.png">

- [x] The footer design is incorrect.
- [x] Between certain breakpoints, there is not spacing between the dashboard cards

<img width="575" alt="Screen Shot 2021-01-29 at 11 55 11 AM" src="https://user-images.githubusercontent.com/5934188/106304093-ed09fa00-6228-11eb-8bc4-62d26b5c9825.png">

- [x] Borders are inconsistent at different breakpoints within the Transactions card

This is what I've caught for now. I will add more as I am able.

2021-01-29 19:06 UTC, icerove commented
will touch again and fix some issues.

2021-02-04 02:36 UTC, thisisjoshford commented
awesome job y'all! 💪  looks like this fixes #527 as well 🙂

2021-02-04 15:53 UTC, corwinharrell requested changes
Looking much better. 2 things I noticed.

1. I'd make a pass over the font-sizes to make sure they are correct. For example, the "View All" links are bigger than the card headings.

2. The indicators in the network dropdown are all the same color, so unless you actually select one, the unique color associated with each ENV is not visible. Each network should be represented by its unique color at all times, including in the dropdown.

2021-02-04 19:33 UTC, frol approved these changes
I believe we can address the last item in a separate PR. I want to release this PR now to address a jumping page issue and unnecessary scroll bars.

2021-02-04 19:34 UTC, merged