feat(frontend): Added 'Charts & Stats' menu item
near/near-explorer pull request #559
Opened 2021-02-22 12:31 UTC by frol

Resolves #558 

@corwinharrell May I ask for a better icon and bikeshed the menu name?

![image](https://user-images.githubusercontent.com/304265/108708781-a5f1ea80-74f0-11eb-9878-4e557431af88.png)

2021-02-22 17:49 UTC, icerove approved these changes

2021-02-22 17:52 UTC, icerove commented
remember to fix test. @frol

2021-02-23 16:55 UTC, corwinharrell commented
@frol I think the label works fine. Here is an alternative icon that matches the style of the rest:

[bar-chart.svg.zip](https://github.com/near/near-explorer/files/6030537/bar-chart.svg.zip)

2021-02-23 16:56 UTC, corwinharrell requested changes
@frol I think the label works fine. Here is an alternative icon that matches the style of the rest:

[bar-chart.svg.zip](https://github.com/near/near-explorer/files/6030542/bar-chart.svg.zip)

2021-02-24 12:46 UTC, merged