feat(frontend): Expose whole pools list
near/near-explorer pull request #661
Opened 2021-06-15 13:37 UTC by shelegdmitriy

Particulary resolves #646

2021-07-29 10:53 UTC, frol commented
## The table does not fit and has a horizontal scroll

![image](https://user-images.githubusercontent.com/304265/127479099-6417cba6-84b1-47b2-8a05-3b4644020cc1.png)

Ideas:

1. Shrink the Stake column by only showing NEAR amounts without any fractional part
2. Shrink some other columns

## The page is super slow

I feel it does too much re-renders, my browser (Firefox) is barely responsive on the page.

## The telemetry data is missing

![image](https://user-images.githubusercontent.com/304265/127479510-36c804fc-d08b-4da2-8163-d1be8cc61a4e.png)

## Add a tooltip to the flags to display the country name

It is not realistic that people would know all the flags by heart.

2021-08-02 14:25 UTC, shelegdmitriy commented
@frol Hey Vlad! I have finished issues above except of _"The telemetry data is missing"_ because it wasn't reproduced. On my local machine all data is available

2021-08-02 14:50 UTC, frol commented
> "The telemetry data is missing"

Oh, my bad, indeed :facepalm:

2021-08-06 15:52 UTC, frol commented
* [ ] Display staked values truncated to the whole NEAR amount [no fractional part]
* [ ] Fix the validators that have no status:
  ![image](https://user-images.githubusercontent.com/304265/128536937-743d6b54-9b9e-4788-bcf1-6bb377656f79.png)
* [ ] Fix unit tests (it seems that we just need to update the snapshot)
* [ ] Check if e2e tests pass on your local machine since nodes list test cannot pass on CI since you updated the backend

2021-08-12 18:37 UTC, frol requested changes

2021-08-12 18:37 UTC, frol commented on frontend/src/components/nodes/ValidatorMetadataRow.tsx
> +              to promote your own node!
Same comment about internationalization. From now on, only add text strings to the transactions files.

2021-08-12 18:37 UTC, frol commented on frontend/src/components/nodes/ValidatorTelemetryRow.tsx
> +                        "Uptime is estimated by the ratio of the number of produced blocks to the number of expected blocks"
Since we are already at it, let's move it to the translations file.

2021-08-16 14:43 UTC, shelegdmitriy commented on frontend/src/translations/vi.global.json
> +        "location": "Location",
Need to translate

2021-08-16 14:44 UTC, shelegdmitriy commented on frontend/src/translations/vi.global.json
> +            "title": "Proposal",
Need to translate title, explain text will be same

2021-08-16 14:44 UTC, shelegdmitriy commented on frontend/src/translations/vi.global.json
> +            "text": "idle node"
Need to translate

2021-08-16 14:45 UTC, shelegdmitriy commented on frontend/src/translations/vi.global.json
> +        "pool_info": {
Need to translate

2021-08-16 14:46 UTC, shelegdmitriy commented on frontend/src/translations/zh-hans.global.json
> +        "location": "Location",
Need to translate

2021-08-16 14:46 UTC, shelegdmitriy commented on frontend/src/translations/zh-hans.global.json
> +            "title": "Proposal",
Need to translate only title

2021-08-16 14:47 UTC, shelegdmitriy commented on frontend/src/translations/zh-hans.global.json
> +        "same_proposed_stake": "same"
Need to translate

2021-08-16 14:47 UTC, shelegdmitriy commented on frontend/src/translations/zh-hans.global.json
> +        }
Need to translate

2021-08-16 21:11 UTC, frol approved these changes

2021-08-18 07:46 UTC, frol requested changes

2021-08-18 07:46 UTC, frol commented on frontend/src/components/nodes/ValidatorTelemetryRow.tsx
> +    if (isTelemetryAvailable) return null;
```suggestion
    if (!isTelemetryAvailable) return null;
```

2021-08-18 07:46 UTC, frol commented on frontend/src/components/nodes/ValidatorsList.tsx
> +    // console.log(validatorsList);
Let's clean it up

2021-08-18 18:06 UTC, frol approved these changes
@shelegdmitriy Well done! Thanks for improving the code clarity and getting through all the subtle details that are super important for the clear picture and improves visibility of the validators network!

2021-08-18 18:07 UTC, merged