Fix: the missing i18n support in the ValidatorRow component
near/near-explorer pull request #706
Opened 2021-08-15 16:29 UTC by IsQiao

Fix: the missing i18n support in the ValidatorRow component
Related PR: #700 
Because I don’t understand Vietnamese, it kept the default in Vietnamese mode
![](https://user-images.githubusercontent.com/34593263/128868543-5dc42250-2e21-4a8d-a537-5b941c01cb05.png)

2021-08-15 17:00 UTC, think-in-universe requested changes
suggestion about Chinese translation

2021-08-15 17:10 UTC, think-in-universe approved these changes

2021-08-15 17:11 UTC, think-in-universe commented
great job! thanks @IsQiao

2021-08-16 12:05 UTC, frol approved these changes

2021-08-16 13:13 UTC, shelegdmitriy approved these changes

2021-08-16 13:14 UTC, merged