refactor(frontend): Move telemetry to database
near/near-explorer pull request #753
Opened 2021-09-30 15:50 UTC by shelegdmitriy

Basicly our telemetry data was stored on a disk and now we want to move those data to gcp database

2021-09-30 15:53 UTC, shelegdmitriy commented on backend/src/db-utils.js
> +      WHERE last_seen > (CAST(EXTRACT(EPOCH FROM DATE_TRUNC('seconds', NOW() - INTERVAL '60 seconds')) AS bigint) * 1000)
@frol  I'm not sure about this condition

2021-10-01 10:04 UTC, frol requested changes
Overall, looks good to me. Please, address the comments

2021-10-01 14:27 UTC, shelegdmitriy commented on backend/src/db-utils.js
> +      WHERE last_seen > (CAST(EXTRACT(EPOCH FROM DATE_TRUNC('seconds', NOW() - INTERVAL '60 seconds')) AS bigint) * 1000)
I've fixed this. It seems there is no need to update `saveNodeIntoDatabase `

2021-10-06 13:38 UTC, frol commented on backend/src/db-utils.js
> +      return models.sequelizeTelemetryBackendReadOnly;
Let's throw an exception here

2021-10-06 13:39 UTC, frol approved these changes

2021-10-12 10:59 UTC, merged