Migrate to Stitches
near/near-explorer pull request #870
Opened 2022-01-25 00:54 UTC by luixo

2022-01-26 22:30 UTC, luixo reviewed
@frol @shelegdmitriy 
Please go through stage thoroughly as we don't have visual tests.
I did my best at comparing current version and upcoming one, but there's no chance everything's perfect.

2022-01-31 12:56 UTC, shelegdmitriy requested changes

2022-01-31 12:57 UTC, shelegdmitriy commented on frontend/src/components/nodes/__test__/__snapshots__/NodesEpoch.test.tsx.snap
> +         L 100,0.5"
I didn't see any difference, so we may skip it

2022-01-31 12:58 UTC, shelegdmitriy commented on frontend/src/components/nodes/__test__/__snapshots__/NodesEpoch.test.tsx.snap
> +              strokeLinecap="square"
Agree, let's skip it

2022-01-31 14:38 UTC, luixo commented on frontend/src/components/dashboard/DashboardBlock.tsx
> +          className="ml-md-4"
To distinct it from other dashboard block in e2e tests.

2022-01-31 14:39 UTC, luixo commented on frontend/src/components/accounts/__tests__/__snapshots__/AccountRow.test.tsx.snap
> +    className="c-LinkWrapper-cIdiJW"
I'm not sure, it's either `class` or `composer` or something like that.
Source: https://github.com/modulz/stitches/blob/59418ebb65f351d9e3bbd4cce211efde24fd9479/packages/core/src/features/css.js#L71

2022-01-31 14:40 UTC, luixo commented on frontend/src/components/utils/DashboardCard.tsx
> +    <div data-id="foo" />
Sorry, didn't remove my test cases :)

2022-01-31 14:54 UTC, luixo commented on frontend/src/components/contracts/ContractDetails.tsx
> +            <LockedCell
That's a good catch.
Actually, `LockedCell` isn't needed at all, all it's styles are overrided deeper in the tree.

2022-01-31 15:02 UTC, luixo commented on frontend/src/components/nodes/NodesCard.tsx
> +    },
There is some misunderstanding here, I believe.
The `stats` page (the one from screenshots) is the same in terms of font size as it is in production.
The `nodes/validators` page (the one from lines you commented) have mentioned font sizes rules applied (you can check green validators amount, for example).

2022-02-01 14:45 UTC, luixo commented
PR is rebased on "providers as hooks" commit, all notes are fixed, ready for you approves 🎉🎉🎉

2022-02-07 14:44 UTC, luixo commented
@shelegdmitriy Please mark PR as approved or clarify problems that were not fixed.

2022-02-07 19:59 UTC, shelegdmitriy approved these changes

2022-02-08 14:09 UTC, frol approved these changes

2022-02-15 22:52 UTC, merged