Fix query to execute contract info
near/near-explorer pull request #887
Opened 2022-02-04 08:20 UTC by shelegdmitriy

Resolves #878

2022-02-04 08:27 UTC, shelegdmitriy commented on backend/src/db-utils.js
> +  const queryContractInfoFromIndexer = async () => {
The thing is this query is running for quite long time (for `near` account as example it takes up to 30s) and you have to wait. We can solve this by returning value from analytics db (it runs very fast) but how about latest contract update if it was?

2022-02-04 08:34 UTC, shelegdmitriy commented on backend/src/db-utils.js
> +  const queryContractInfoFromIndexer = async () => {
We can split it into two queries:
 - the first query from analytics to find and return contract info as fast as we can;
 - the second one to query from indexer db
All this queries will be runned one by one from the component. If there is some fresh data the section with contract will be updated.
But I'm not sure. @frol WDYT?

2022-02-09 13:26 UTC, frol requested changes

2022-02-09 13:26 UTC, frol commented on backend/src/db-utils.js
> +  const queryLatestHistoricalInfo = async () => {
1. Fix the order of requests as per offline discussion
2. Avoid unnecessary functions

2022-02-09 13:26 UTC, frol commented on backend/src/db-utils.js
> +        : undefined,
Move div to the query (database)

2022-02-15 22:31 UTC, luixo commented
I still [don't see](https://near-explorer-experimental-frontend-with-i3mp.onrender.com/accounts/near) contract info on `near` account. Should I?

2022-02-16 09:07 UTC, shelegdmitriy commented
> don't see

No, because we don't deploy backend on preview. You can only see it on local machine

2022-02-16 11:22 UTC, frol commented
@luixo Just for the reference, I checked it on localhost:

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/304265/154254792-b42080a3-0347-4254-8773-24ce7007b559.png">

2022-02-16 12:51 UTC, merged